# Generated by Django 2.2.5 on 2019-11-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('pelicula_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pelicula', models.CharField(max_length=75, unique=True)),
                ('sinopsis', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('A', '"A" - Aptas para todo publico'), ('B', '"B" - Películas para adolescentes de 12 años en adelante'), ('B15', '"B15" - Película no recomendable para menores de 15 años de edad'), ('C', '"C" - Películas para adultos de 18 años en adelante'), ('D', '"D" - Películas para adultos, con sexo explícito')], default='"A" - Aptas para todo publico', max_length=15)),
                ('fechaLanzamiento', models.DateField()),
                ('duracion', models.CharField(max_length=25)),
                ('estado', models.BooleanField(choices=[('True', 'Si'), ('False', 'No')])),
                ('director', models.CharField(max_length=25)),
                ('protagonistas', models.TextField(default='n/a', max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='portadas')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=75, unique=True)),
                ('apellidos', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('edad', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=50)),
                ('rol', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(max_length=75, unique=True)),
                ('nro_asientos', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario_id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_pelicula', models.TimeField()),
                ('fecha_pelicua', models.DateField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('boleto_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_asientos', models.IntegerField(max_length=10)),
                ('precio_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('especial', 'Especial')], default='Normal', max_length=30)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Horario')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona')),
            ],
        ),
    ]
