# Generated by Django 2.2.5 on 2020-01-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=75, unique=True)),
            ],
        ),
    ]
