# Generated by Django 2.2.5 on 2019-11-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='proyeccion',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=15),
        ),
    ]
